language: c++
os:
  - linux
  - osx
osx_image: xcode6.4
sudo: required
before_install:
  - git submodule update --init --recursive
install:
  # source because it sets up env vars on some platforms
  - source ./travis_install.sh
compiler:
  - gcc
script: ./run_tests.py
env:
  - USE_CLANG_COMPLETER="true" YCMD_PYTHON_VERSION="2.6"
  - USE_CLANG_COMPLETER="false" YCMD_PYTHON_VERSION="2.7"
  - USE_CLANG_COMPLETER="true" YCMD_PYTHON_VERSION="2.7"
  - USE_CLANG_COMPLETER="false" YCMD_PYTHON_VERSION="2.6"
