sudo: false
language: csharp
mono:
  - beta
os:
  - linux
  #- osx
before_install:
  - git submodule update --init --recursive
install:
  - export YCMD_VENV_DIR=${HOME}/venvs/ycmd_test
  - mkdir ${HOME}/bin
  - export PATH=${HOME}/bin:$PATH
  - ln -s /usr/bin/g++-4.8 ${HOME}/bin/g++
  - ln -s /usr/bin/gcc-4.8 ${HOME}/bin/gcc
  - ln -s ${HOME}/bin/g++ ${HOME}/bin/c++
  - virtualenv -p python${PYTHON_VERSION} $YCMD_VENV_DIR
  - cp /usr/bin/python${PYTHON_VERSION}-config ${YCMD_VENV_DIR}/bin/python-config
  - source ${YCMD_VENV_DIR}/bin/activate
  - pip install -U pip wheel setuptools
  - pip install -r test_requirements.txt
  - npm install -g typescript
  # Travis can run out of RAM when compiling if don't prevent parallelization.
  - export YCM_CORES=1
compiler:
  - gcc
  - clang
before_script:
  - if [ $TRAVIS_OS_NAME == "osx" ] ; then sudo sysctl -w kern.maxfiles=64000 ; sudo sysctl -w kern.maxfilesperproc=64000 ; sudo launchctl limit maxfiles 64000 64000 ; fi ; ulimit -n 64000
script: ./run_tests.py
env:
  - PYTHON_VERSION="2.6" USE_CLANG_COMPLETER="true" MONO_THREADS_PER_CPU=2000 MONO_MANAGED_WATCHER=disabled
  - PYTHON_VERSION="2.6" USE_CLANG_COMPLETER="false" MONO_THREADS_PER_CPU=2000 MONO_MANAGED_WATCHER=disabled
  - PYTHON_VERSION="2.7" USE_CLANG_COMPLETER="true" MONO_THREADS_PER_CPU=2000 MONO_MANAGED_WATCHER=disabled
  - PYTHON_VERSION="2.7" USE_CLANG_COMPLETER="false" MONO_THREADS_PER_CPU=2000 MONO_MANAGED_WATCHER=disabled
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - deadsnakes
    packages:
     - g++-4.8
     - python2.6
     - python2.6-dev
     - python2.7
     - python2.7-dev
     - python-virtualenv
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.dnx/packages
