language: csharp
os:
  - linux
  - osx
sudo: false
mono:
  - beta
before_install:
  - git submodule update --init --recursive
install:
  # source because it sets up env vars on some platforms
  - source ./travis_install.sh
compiler:
  - gcc
script: ./run_tests.py
env:
  - USE_CLANG_COMPLETER="true" YCMD_PYTHON_VERSION="2.6" MONO_THREADS_PER_CPU=2000 MONO_MANAGED_WATCHER=disabled
  - USE_CLANG_COMPLETER="false" YCMD_PYTHON_VERSION="2.7" MONO_THREADS_PER_CPU=2000 MONO_MANAGED_WATCHER=disabled
  - USE_CLANG_COMPLETER="true" YCMD_PYTHON_VERSION="2.7" MONO_THREADS_PER_CPU=2000 MONO_MANAGED_WATCHER=disabled
  - USE_CLANG_COMPLETER="false" YCMD_PYTHON_VERSION="2.6" MONO_THREADS_PER_CPU=2000 MONO_MANAGED_WATCHER=disabled
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - deadsnakes
    packages:
     - g++-4.8
     - python2.6
     - python2.6-dev
     - python2.7
     - python2.7-dev
     - python-virtualenv
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.dnx/packages
